#!/bin/bash

# Made by Arctine Laboratories, for ArctineOS. Licensed under GPL together with ArctineOS!

ArCLI_DIR="/Arctine/Tools/ArCLI/"
ArCLI_VER="26.4"

function scriptcolors() {
    # Reset
    export Color_Off='\033[0m'       # Text Reset

    # Regular Colors
 
    # Bold
    export BRed='\033[1;31m'         # Red
    export BYellow='\033[1;33m'      # Yellow
    export BBlue='\033[1;34m'        # Blue
    export BCyan='\033[1;36m'        # Cyan
 
    echo -e "${BBlue}[i] The colour variables have been set.${Color_Off}"
}

scriptcolors

limsg() {
    # LiMSG, as seen in the TyrianOS builder.
    case $1 in
        s)
            lmsg_one="STAGE"
        ;;

    esac
    lmsg_two=$2
    case $3 in
        i)
            lmsg_three="${BBlue}INFO"
        ;;
        w)
            lmsg_three="${BYellow}WARN"
        ;;
        e)            
            lmsg_three="${BRed}ERRR"
        ;;
        *)
            lmsg_three=$3
        ;;
    esac
    echo -e "[ArCLI(LiMSG)/${BCyan}${lmsg_one} ${lmsg_two}${Color_Off}/${lmsg_three}${Color_Off}]: $4"
}

# Load locales
#case $LANG in
#    C*)
#        # shellcheck disable=SC1091
#        source ../../../Library/Translations/ArCLI/Executable/en.arctinelocale || limsg s 1 e "Could not find debug locale"
#    ;;
#    *)
#        # shellcheck disable=SC1091
#        source /Arctine/Library/Translations/ArCLI/Executable/en.arctinelocale || limsg s 1 e "Could not find the locale file en.arctinelocale in /Arctine/Library/Translations/ArCLI/Executable/."
#    ;;
#esac

main() {
    case "$1" in
        "-v"|"--version"|"about")
            about
        ;;
        "-h"|"--help"|"help")
            help
        ;;
        "permifix"|"--permifix")
            modules.permifix
        ;;
        *)
            modulerun "$@" || limsg s 1 e "Failed to run command $*. If you're sure the module exists, try running arcli permifix to repair executable permissions?"
        ;;
    esac
}

modules.list() {
    for arcli_module in "$ArCLI_DIR/Modules"/*; do
        $arcli_module "$@"
        module_name=${arcli_module##*/}
        export "$(grep -a -h -m 1 'arclimod_Version=' $ArCLI_DIR/Modules/"$module_name" | head -1)" || limsg s 1 e "Failed to get version for $module_name."
        echo "$module_name · $arclimod_Version"
    done
}

modules.permifix() {
    limsg s 1 i "Requesting sudo access for making ArCLI modules executable..."
    sudo chmod +x $ArCLI_DIR/Modules/* || limsg s 1 e "The command failed."
}

help() {
    # shellcheck disable=SC2154
    echo "ArCLI - ArctineOS CLI Tool

arcli help|-h|--help · display this message
arcli modules · manage modules through this command line interface
arcli modules list · list installed modules
arcli permifix · Make ArCLI modules executable
arcli about · show about"
    for arcli_module in "$ArCLI_DIR/Modules"/*; do
        $arcli_module help
    done
}

about() {
    echo "ArCLI (ArctineOS CLI) $ArCLI_VER
(Ↄ) Arctine Laboratories 2026"
}

modulerun_all() {
    for arcli_module in "$ArCLI_DIR/Modules"/*.arclimod; do
        $arcli_module "$@"
    done
}

modulerun() {
    "$ArCLI_DIR/Modules/$1.arclimod" "${@:2}"
}

main "$@"