#!/bin/bash

# (C) ArctineLabs, 2026.

main() {
    if gui; then
        FUNC=$(declare -f upgrade)
        FUNC2=$(declare -f error)
        sudo -A bash -c "$FUNC; $FUNC2; upgrade"
    else
        if [[ $GUI_OPTION == "View commit history" ]]; then
            xdg-open https://github.com/ArctineLabs/OS/commits/main/
        else
            exit 1
        fi
    fi
}

gui() {
    # shellcheck disable=SC1091
    source /etc/os-release
    GUI_OPTION=$(zenity --question --title="Update ArctineOS" \
        --text="$(pacman -Qiq milanium | head -n 2)" \
        --ok-label "Check and update system" \
        --cancel-label "Exit updater" \
        --extra-button "View release history" \
        --icon software-update-available-symbolic) || export EXIT=yes
    export GUI_OPTION
    if [[ $EXIT == "yes" ]]; then
        false
        return 1
    else
        true
    fi
#        --text="wawa" \
}

upgrade() {
    # run bootc upgrade with administrative perms | take the output of the command and forward it except every line starts with # | render it in Zenity
    sudo -A bootc upgrade | while IFS= read -r line; do echo "# $line"; done | zenity --progress --title=Updating system... --pulsate
}

error() {
    zenity --error --text="$1"
    exit 1
}

main