#!/bin/bash

# (C) ArctineLabs, 2026.

main() {
    if gui; then
        FUNC=$(declare -f upgrade)
        sudo bash -c "$FUNC; upgrade"
    else
        if [[ $GUI_OPTION == "View commit history" ]]; then
            xdg-open https://github.com/ArctineLabs/OS/commits/main/
        else
            exit 1
        fi
    fi
}

gui() {
    GUI_OPTION=$(zenity --question --title="Update ArctineOS" \
        --text="wawa" \
        --ok-label "Update system" \
        --cancel-label "Exit updater" \
        --extra-button "View commit history" \
        --icon software-update-available-symbolic) || export EXIT=yes
    export GUI_OPTION
    if [[ $EXIT == "yes" ]]; then
        false
        return 1
    else
        true
    fi
#        --text="$(pacman -Qiq milanium | head -n 2)" \
}

upgrade() {
    if zenity --question --text "Perform system update?\nSave all unsaved work, as this will restart your device."; then
        true
    else
        exit 1
    fi

    (
        echo "11"
        echo "# Discarding any changes made in the source code directory..."
        git stash || error "Failed to stash commits"
        echo "22"
        echo "# Pulling latest commits from OS source..."
        git pull || error "Failed to pull"
        echo "33"
        echo "# Making sure \"nobody:nobody\" owns the OS source directory..."
        chown nobody:nobody -Rv . || error "Failed to change ownership to nobody:nobody"
        echo "44"
        echo "# Sourcing PKGBUILD..."
        source PKGBUILD || error "Failed to source PKGBUILD"
        echo "55"
        echo "# Updating all installed packages..."
        pacman -Syu --noconfirm || error "Failed to update all packages"
        echo "66"
        echo "# Installing all needed dependencies for the update..."
        # shellcheck disable=SC2154
        pacman -S "${depends[@]}" --noconfirm --needed || error "Failed to install dependencies"
        echo "77"
        echo "# Building update package..."
        sudo -u nobody makepkg -srf || error "Failed to build update package"
        echo "88"
        echo "# Installing update..."
        # shellcheck disable=SC2154
        pacman -Uv ./"${pkgname}"-"${pkgver}"-"${pkgrel}"-"${arch[*]}".pkg.tar.zst --noconfirm || error "Failed to install update"
        echo "99"
        echo "# Finishing up..."
        chmod +x /Arctine/Tools/ArCLI/Modules/* || error "Failed to add executable flag to ArCLI modules"
        echo "100"
        echo "# Restarting..."
        sleep 0.5;reboot
    ) | zenity --progress \
  --title="Updating system..." \
  --text="Preparation..." \
  --percentage=0 \
  --no-cancel \
  --time-remaining
}

error() {
    zenity --error --text="$1"
    exit 1
}

main