#!/bin/bash

# 0BSD license
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.

error() {
	case $1 in
		6)
			echo "Error with hook.filesystem()!"
			exit 1
		;;
		*)
			echo "Unknown error code $1!"
			exit 1
		;;
	esac

}

hook.filesystem() {
	cp -vr /Arctine/Filesystem/Replace/* / || error 6
}

main() {
	case $1 in
		filesystem)
			hook.filesystem
		;;
		*)
			echo "Unknown hook: $1"
		;;
	esac
}

main "$@"
